import { useEffect, useState } from 'react'
import { getCaptionDisplay } from './captionDisplayEngine'
import type { CaptionRevealMode, CaptionRevealSettings } from './types'
import type { CaptionSegment } from '../types/video'

const modes: Array<{ id: CaptionRevealMode; name: string; category: string }> = [
  { id: 'full-phrase', name: 'Full phrase', category: 'Phrases' }, { id: 'smart-chunks', name: 'Smart chunks', category: 'Phrases' },
  { id: 'two-words', name: 'Two words', category: 'Phrases' }, { id: 'three-words', name: 'Three words', category: 'Phrases' },
  { id: 'line-by-line', name: 'Line by line', category: 'Phrases' }, { id: 'line-replace', name: 'Line replace', category: 'Phrases' },
  { id: 'speaker-subtitle', name: 'Speaker subtitle', category: 'Phrases' }, { id: 'cinema-subtitle', name: 'Cinema subtitle', category: 'Phrases' },
  { id: 'single-word', name: 'Single word', category: 'Words' }, { id: 'word-replace', name: 'Word replace', category: 'Words' },
  { id: 'word-build', name: 'Word build', category: 'Words' }, { id: 'progressive-build', name: 'Progressive build', category: 'Words' },
  { id: 'rapid-fire', name: 'Rapid fire', category: 'Words' }, { id: 'slow-read', name: 'Slow read', category: 'Words' },
  { id: 'letter-by-letter', name: 'Letter by letter', category: 'Typing' }, { id: 'letter-build', name: 'Letter build', category: 'Typing' },
  { id: 'letter-replace', name: 'Letter replace', category: 'Typing' }, { id: 'typewriter-phrase', name: 'Typewriter phrase', category: 'Typing' },
  { id: 'active-word', name: 'Active word', category: 'Tracking' }, { id: 'active-word-fade', name: 'Active word fade', category: 'Tracking' },
  { id: 'active-word-scale', name: 'Active word scale', category: 'Tracking' }, { id: 'active-word-box', name: 'Active word box', category: 'Tracking' },
  { id: 'karaoke', name: 'Karaoke', category: 'Tracking' }, { id: 'karaoke-sweep', name: 'Karaoke sweep', category: 'Tracking' },
  { id: 'focus-word', name: 'Focus word', category: 'Tracking' }, { id: 'underline-track', name: 'Underline track', category: 'Tracking' },
  { id: 'bold-track', name: 'Bold track', category: 'Tracking' }, { id: 'size-track', name: 'Size track', category: 'Tracking' },
  { id: 'opacity-track', name: 'Opacity track', category: 'Tracking' }, { id: 'teleprompter-build', name: 'Teleprompter build', category: 'Tracking' },
  { id: 'keyword-only', name: 'Keyword only', category: 'Special' }, { id: 'keyword-hero', name: 'Keyword hero', category: 'Special' },
  { id: 'number-hero', name: 'Number hero', category: 'Special' }, { id: 'question-answer', name: 'Question / answer', category: 'Special' },
  { id: 'stack-build', name: 'Stack build', category: 'Special' }, { id: 'vertical-word-stack', name: 'Vertical word stack', category: 'Special' },
  { id: 'left-right-alternate', name: 'Left / right', category: 'Special' }, { id: 'social-clean', name: 'Social clean', category: 'Special' },
  { id: 'social-highlight', name: 'Social highlight', category: 'Special' }, { id: 'word-card', name: 'Word card', category: 'Special' },
  { id: 'active-card', name: 'Active card', category: 'Special' },
]

const example: CaptionSegment[] = [{ id: 'preview', start: 0, end: 2.4, words: ['MAKE', 'BETTER', 'CONTENT'].map((text, index) => ({
  id: `preview-${index}`, text, start: index * .8, end: (index + 1) * .8, confidence: 1, emphasis: index === 2,
})) }]

export function RevealControls({ reveal, onPatch }: { reveal: CaptionRevealSettings; onPatch: (patch: Partial<CaptionRevealSettings>) => void }) {
  const [time, setTime] = useState(0)
  const [query, setQuery] = useState('')
  const [categoryFilter, setCategoryFilter] = useState('All')
  useEffect(() => { const timer = window.setInterval(() => setTime((value) => (value + .16) % 2.4), 160); return () => window.clearInterval(timer) }, [])
  const typing = ['letter-by-letter', 'letter-build', 'letter-replace', 'typewriter-phrase'].includes(reveal.mode)
  const categories = [...new Set(modes.map((mode) => mode.category))]
  const groups = categories.filter((category) => (categoryFilter === 'All' || categoryFilter === category) && modes.some((mode) => mode.category === category && mode.name.toLowerCase().includes(query.toLowerCase())))
  return <div className="space-y-5 pt-4">
    <div><h3 className="text-sm font-semibold text-white">Caption flow</h3><p className="mt-1 text-[11px] text-zinc-500">Choose how spoken words appear.</p></div>
    <input aria-label="Search reveal modes" placeholder="Search caption flow…" value={query} onChange={(event) => setQuery(event.target.value)} className="h-9 w-full rounded border border-white/10 bg-black/30 px-3 text-xs text-white placeholder:text-zinc-600" />
    <div className="flex flex-wrap gap-1">{['All', ...categories].map((category) => <button key={category} type="button" onClick={() => setCategoryFilter(category)} className={`rounded border px-2 py-1 text-[9px] ${categoryFilter === category ? 'border-lime-300 text-lime-300' : 'border-white/10 text-zinc-500'}`}>{category}</button>)}</div>
    {groups.map((category) => <section key={category}><h4 className="mb-2 text-[9px] font-bold uppercase tracking-[.16em] text-zinc-500">{category}</h4><div className="grid grid-cols-2 gap-2">{modes.filter((mode) => mode.category === category && mode.name.toLowerCase().includes(query.toLowerCase())).map((mode) => {
      const preview = getCaptionDisplay(example, time, { ...reveal, mode: mode.id, wordsPerPage: 3, wordsPerLine: 3, clearOnPause: false })
      return <button key={mode.id} type="button" onClick={() => onPatch({ mode: mode.id })} aria-pressed={reveal.mode === mode.id} className={`min-h-20 rounded-lg border p-2.5 text-left transition ${reveal.mode === mode.id ? 'border-lime-300 bg-lime-300/10' : 'border-white/10 bg-white/[.025] hover:border-white/30'}`}>
        <span className="flex min-h-9 items-center justify-center gap-1 overflow-hidden text-center text-[10px] font-black leading-tight text-white">{preview?.words.map(({ word, text, state }) => <span key={word.id} className={state === 'active' ? 'text-lime-300' : 'text-zinc-400'}>{text}</span>) ?? '···'}</span>
        <span className="mt-1 block text-[9px] font-semibold text-zinc-400">{mode.name}</span>
      </button>
    })}</div></section>)}
    <section className="space-y-3 border-t border-white/10 pt-4"><h4 className="text-[9px] font-bold uppercase tracking-[.16em] text-zinc-500">Grouping and timing</h4>
      <div className="grid grid-cols-2 gap-2"><NumberField label="Words per page" value={reveal.wordsPerPage} min={1} max={12} onChange={(wordsPerPage) => onPatch({ wordsPerPage })} /><NumberField label="Words per line" value={reveal.wordsPerLine} min={1} max={8} onChange={(wordsPerLine) => onPatch({ wordsPerLine })} /><NumberField label="Lines per page" value={reveal.linesPerPage} min={1} max={3} onChange={(linesPerPage) => onPatch({ linesPerPage })} /><NumberField label="Pause threshold (ms)" value={reveal.pauseThresholdMs} min={100} max={1000} step={50} onChange={(pauseThresholdMs) => onPatch({ pauseThresholdMs })} /><NumberField label="Pre-roll (ms)" value={reveal.preRollMs} min={0} max={250} step={10} onChange={(preRollMs) => onPatch({ preRollMs })} /><NumberField label="Post-roll (ms)" value={reveal.postRollMs} min={0} max={400} step={10} onChange={(postRollMs) => onPatch({ postRollMs })} /><NumberField label="Active word lead (ms)" value={reveal.activeWordLeadMs} min={0} max={250} step={10} onChange={(activeWordLeadMs) => onPatch({ activeWordLeadMs })} /></div>
      <div className="grid grid-cols-2 gap-2"><NumberField label="Minimum page (ms)" value={reveal.minimumDurationMs ?? 0} min={0} max={3000} step={100} onChange={(minimumDurationMs) => onPatch({ minimumDurationMs })} /><NumberField label="Maximum page (ms)" value={reveal.maximumDurationMs ?? 2600} min={500} max={6000} step={100} onChange={(maximumDurationMs) => onPatch({ maximumDurationMs })} /></div>
      <Select label="Pace" value={reveal.pace ?? 'normal'} options={[["relaxed","Relaxed"],["normal","Normal"],["fast","Fast"],["rapid","Rapid"]]} onChange={(pace) => onPatch({ pace: pace as CaptionRevealSettings['pace'] })} />
      <Select label="After a group finishes" value={reveal.clearBehavior ?? 'next-word'} options={[["replace","Clear immediately"],["hold","Hold briefly"],["fade","Fade later"],["next-word","Wait for next word"]]} onChange={(clearBehavior) => onPatch({ clearBehavior: clearBehavior as CaptionRevealSettings['clearBehavior'] })} />
      <Toggle label="Clear during pauses" value={reveal.clearOnPause} onChange={(clearOnPause) => onPatch({ clearOnPause })} />
      <Toggle label="Keep built words" value={reveal.buildKeepsPreviousWords} onChange={(buildKeepsPreviousWords) => onPatch({ buildKeepsPreviousWords })} />
      {['stack-build', 'vertical-word-stack'].includes(reveal.mode) && <Select label="Stack direction" value={reveal.stackDirection ?? 'top-down'} options={[["top-down", "Top down"], ["bottom-up", "Bottom up"]]} onChange={(stackDirection) => onPatch({ stackDirection: stackDirection as CaptionRevealSettings['stackDirection'] })} />}
    </section>
    {typing && <section className="space-y-3 border-t border-white/10 pt-4"><h4 className="text-[9px] font-bold uppercase tracking-[.16em] text-zinc-500">Letter reveal</h4><Select label="Speed mode" value={reveal.typingSpeedMode ?? 'speech'} options={[['speech', 'Sync to speech'], ['fixed', 'Fixed speed']]} onChange={(typingSpeedMode) => onPatch({ typingSpeedMode: typingSpeedMode as CaptionRevealSettings['typingSpeedMode'] })} /><NumberField label="Characters per second" value={reveal.charactersPerSecond} min={2} max={60} onChange={(charactersPerSecond) => onPatch({ charactersPerSecond })} /><Select label="Cursor" value={reveal.cursor} options={[['off', 'Off'], ['bar', 'Bar |'], ['underscore', 'Underscore _'], ['block', 'Block █']]} onChange={(cursor) => onPatch({ cursor: cursor as CaptionRevealSettings['cursor'] })} /><NumberField label="Cursor blink (ms)" value={reveal.cursorBlinkMs ?? 500} min={0} max={1000} step={100} onChange={(cursorBlinkMs) => onPatch({ cursorBlinkMs })} /></section>}
    <section className="space-y-3 border-t border-white/10 pt-4"><h4 className="text-[9px] font-bold uppercase tracking-[.16em] text-zinc-500">Active and inactive words</h4><div className="grid grid-cols-2 gap-2"><ColorField label="Past color" value={reveal.pastColor ?? '#ffffff'} onChange={(pastColor) => onPatch({ pastColor })} /><ColorField label="Current color" value={reveal.activeColor ?? '#d9ff5b'} onChange={(activeColor) => onPatch({ activeColor })} /><ColorField label="Future color" value={reveal.futureColor ?? '#777777'} onChange={(futureColor) => onPatch({ futureColor })} /><ColorField label="Active background" value={reveal.activeBackground ?? '#d9ff5b'} onChange={(activeBackground) => onPatch({ activeBackground })} /></div><NumberField label="Active scale %" value={Math.round((reveal.activeScale ?? 1.12) * 100)} min={100} max={150} onChange={(value) => onPatch({ activeScale: value / 100 })} /><Select label="Active font weight" value={String(reveal.activeFontWeight ?? 900)} options={[["400","Regular"],["700","Bold"],["900","Black"]]} onChange={(value) => onPatch({ activeFontWeight: Number(value) })} /><div className="grid grid-cols-2 gap-2"><Toggle label="Underline" value={Boolean(reveal.activeUnderline)} onChange={(activeUnderline) => onPatch({ activeUnderline })} /><Toggle label="Glow" value={Boolean(reveal.activeGlow)} onChange={(activeGlow) => onPatch({ activeGlow })} /><Toggle label="Stroke" value={Boolean(reveal.activeStroke)} onChange={(activeStroke) => onPatch({ activeStroke })} /></div></section>
    {typing && <Select label="Character direction" value={reveal.characterDirection ?? 'ltr'} options={[["ltr", "Left to right"], ["rtl", "Right to left"]]} onChange={(characterDirection) => onPatch({ characterDirection: characterDirection as CaptionRevealSettings['characterDirection'] })} />}
    <section className="space-y-2 border-t border-white/10 pt-4"><h4 className="text-[9px] font-bold uppercase tracking-[.16em] text-zinc-500">Tracking details</h4><div className="grid grid-cols-2 gap-2"><NumberField label="Past opacity %" value={Math.round((reveal.pastOpacity ?? .68) * 100)} min={0} max={100} onChange={(value) => onPatch({ pastOpacity: value / 100 })} /><NumberField label="Current opacity %" value={Math.round((reveal.currentOpacity ?? 1) * 100)} min={0} max={100} onChange={(value) => onPatch({ currentOpacity: value / 100 })} /><NumberField label="Future opacity %" value={Math.round((reveal.futureOpacity ?? .48) * 100)} min={0} max={100} onChange={(value) => onPatch({ futureOpacity: value / 100 })} /></div><div className="grid grid-cols-2 gap-2"><Select label="Past weight" value={String(reveal.pastWeight ?? 700)} options={[["400","Regular"],["700","Bold"],["900","Black"]]} onChange={(value) => onPatch({ pastWeight: Number(value) })} /><Select label="Future weight" value={String(reveal.futureWeight ?? 700)} options={[["400","Regular"],["700","Bold"],["900","Black"]]} onChange={(value) => onPatch({ futureWeight: Number(value) })} /></div></section>
  </div>
}

function NumberField({ label, value, min, max, step = 1, onChange }: { label: string; value: number; min: number; max: number; step?: number; onChange: (value: number) => void }) { return <label className="block text-[9px] text-zinc-500">{label}<input className="mt-1 h-9 w-full rounded border border-white/10 bg-black/30 px-2 text-xs text-white" type="number" value={value} min={min} max={max} step={step} onChange={(event) => onChange(Math.min(max, Math.max(min, Number(event.target.value))))} /></label> }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <label className="block text-[9px] text-zinc-500">{label}<select className="mt-1 h-9 w-full rounded border border-white/10 bg-black/30 px-2 text-xs text-white" value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label> }
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <button type="button" onClick={() => onChange(!value)} className={`flex w-full items-center justify-between rounded border px-3 py-2 text-[10px] ${value ? 'border-lime-300/50 text-lime-300' : 'border-white/10 text-zinc-500'}`}><span>{label}</span><span>{value ? 'On' : 'Off'}</span></button> }
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-[9px] text-zinc-500">{label}<span className="mt-1 flex h-9 items-center gap-2 rounded border border-white/10 bg-black/30 px-2"><input type="color" value={value} onChange={(event) => onChange(event.target.value)} className="size-5" /><span className="text-[10px] text-white">{value}</span></span></label> }
